### ISSUE TITLE
Training problem: KeyError: 'scale_invariant_signal_noise_ratio'

### ISSUE THREAD

**Issue by wenyuc55** [vb000/Waveformer#10]
I have done the training step now, but now I get an error

(wave-env) ziyu@ziyu:~/桌面/wenyu/Waveformer/Waveformer-main$ python3 -W ignore -m src.training.train experiments/dcc_tf_ckpt_E256_10_D128_1 --use_cuda
Imported the model from 'src.training.dcc_tf'.
Loading train dataset: fg_dir=data/FSDSoundScapes/FSDKaggle2018/train bg_dir=data/FSDSoundScapes/TAU-acoustic-sounds/TAU-urban-acoustic-scenes-2019-development
Loaded train dataset at data/FSDSoundScapes containing 50000 elements
Loading val dataset: fg_dir=data/FSDSoundScapes/FSDKaggle2018/val bg_dir=data/FSDSoundScapes/TAU-acoustic-sounds/TAU-urban-acoustic-scenes-2019-development
Loaded test dataset at data/FSDSoundScapes containing 5000 elements
Using CUDA devices: [0]
Initializing optimizer with {'lr': 0.0005, 'weight_decay': 0.0}
Learning rates initialized to: {group 0: params=1.04749M lr=5.0E-04}
Initialized LR scheduler with params: fix_lr_epochs=50 {'mode': 'max', 'factor': 0.1, 'patience': 5, 'min_lr': 5e-06, 'threshold': 0.1, 'threshold_mode': 'abs'}
Epoch 0:
Train: 100%|█████████████████████████████████████| 6250/6250 [39:44<00:00,  2.62it/s, loss=-1.42589]
Train: _signal_noise_ratio=7.8949 _scale_invariant_signal_noise_ratio=2.9086 loss=-0.9241
Test:   0%|                                                                  | 0/79 [00:00<?, ?it/s]STAGE:2024-04-27 16:52:06 11298:11298 ActivityProfilerController.cpp:314] Completed Stage: Warm Up
STAGE:2024-04-27 16:52:08 11298:11298 ActivityProfilerController.cpp:320] Completed Stage: Collection
STAGE:2024-04-27 16:52:08 11298:11298 ActivityProfilerController.cpp:324] Completed Stage: Post Processing
Test:   0%|                                                                  | 0/79 [01:28<?, ?it/s]
Traceback (most recent call last):
  File "/home/ziyu/桌面/wenyu/Waveformer/Waveformer-main/src/training/train.py", line 200, in train
    curr_test_metrics = test_epoch(model, device, val_loader,
  File "/home/ziyu/桌面/wenyu/Waveformer/Waveformer-main/src/training/eval.py", line 89, in test_epoch
    tensorboard_add_metrics(
  File "/home/ziyu/桌面/wenyu/Waveformer/Waveformer-main/src/training/synthetic_dataset.py", line 162, in tensorboard_add_metrics
    vals = np.asarray(metrics['scale_invariant_signal_noise_ratio'])
KeyError: 'scale_invariant_signal_noise_ratio'

**Comment by wenyuc55** [comment]
I use ubuntu system to run the code.
